tools:
    shell:
        allow:
            - ls *
            - file *
            - echo *
            - head *
            - cd *
            - find *
            - sort
            - cat *
            - grep *
            - npx vitest run *
            - command *
            - node *
            - node_modules/.bin/vitest run *
            - tail *
            - bun test *
            - sed *
            - curl *
            - sort *
            - rm *
            - bun *
            - bunx eslint *
            - bunx tsc *
            - git status *
