tools:
    shell:
        allow:
            - ls *
            - find *
            - echo *
            - cd *
            - head *
            - cat *
            - grep *
            - sips *
            - python3 *
paths:
    allow:
        - path: /Users/apple/work/launchcrew/**
